config/routes.rb
Rails.application.routes.draw do
  get "categories/index"

  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  get "/carts", to: "carts#index"
  post "/carts", to: "carts#create"
  put "/carts", to: "carts#update"
  delete "/carts", to: "carts#destroy"
  resources :users do
    resources :suggested_products
    resources :orders, only: [:show]
  end
  resources :products do
    resources :ratings, only: :create
  end
  resources :carts, only: :index
  resources :orders
  resources :order_confirmations, only: :edit
  namespace :admin do
    resources :products do
      collection {post :import}
    end
    resources :users, only: [:index, :destroy]
    resources :orders
    resources :suggested_products, only: [:index, :destroy]
    resources :statistics
    resources :categories
    resources :sub_categories
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explaination">
    <div class="alert alert-danger">
      <%= t("error_page.the_form_contains")
        pluralize(object.errors.count, "error")%>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_search_form.html.erb
<%= form_tag yield(:path), method: :get do %>
  <div>
    <%= t "search_form.name" %><%= text_field_tag "name", params[:name],
      class: "form-control" %>
  </div>
  <div><%= t "search_form.category" %><%= select_tag "sub_category",
    grouped_options_for_select(group_category_select, params[:sub_category]),
    class: "select form-control",
    include_blank: "All" %>
  </div>
  <div><%= t "search_form.classification" %><%= select_tag "classification",
    options_for_select(classification_select, params[:classification]),
    class: "select form-control", include_blank: t("select.select_all") %>
  </div>
  <div><%= t "search_form.rating" %><%= select_tag "rate",
    options_for_select(rate_select, params[:rate]), class: "select form-control",
    include_blank: "All" %>
  </div>
  <div class="price-slider">
    <label><%= t "search_form.price" %></label>
    <label><%= number_to_currency Settings.search_form.min_price %></label>
    <div class="slider-wrapper">
      <%= text_field_tag "price", "", id: "price-slider", type: "text",
        "data-slider-min": Settings.search_form.min_price,
        "data-slider-max": Settings.search_form.max_price,
        "data-slider-step": Settings.search_form.slider_step,
        "data-slider-value": Settings.search_form.slider_value,
        "data-slider-orientation": "vertical"%>
    </div>
    <label><%= number_to_currency Settings.search_form.max_price %></label>
  </div>
  <button type="submit" class="btn btn-primary full-width-button">
    <%= t "search_form.search" %>
  </button>
  <% if yield(:path) == admin_products_path %>
    <div class="upload-section">
      <a class="text-danger" data-toggle="modal" data-target="#upload-modal">
        <%= t "upload_csv" %>
      </a>
    </div>
  <% end %>
<% end %>