config/routes.rb
Rails.application.routes.draw do
  get "categories/index"

  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  get "/carts", to: "carts#index"
  post "/carts", to: "carts#create"
  put "/carts", to: "carts#update"
  delete "/carts", to: "carts#destroy"
  resources :users do
    resources :suggested_products
    resources :orders, only: [:show]
  end
  resources :products do
    resources :ratings, only: :create
  end
  resources :carts, only: :index
  resources :orders
  resources :order_confirmations, only: :edit
  namespace :admin do
    resources :products do
      collection {post :import}
    end
    resources :users, only: [:index, :destroy]
    resources :orders
    resources :suggested_products, only: [:index, :destroy]
    resources :statistics
    resources :categories
    resources :sub_categories
  end
end

app/controllers/admin/statistics_controller.rb
class Admin::StatisticsController < ApplicationController
  before_action :admin_user
  def index
    @day = params[:date].present? ? params[:date].to_date : Date.new
    @select = params[:statistic]
  end
end

app/helpers/admin/statistics_helper.rb
module Admin::StatisticsHelper
  def render_chart chart_type
    case chart_type
    when Settings.chart_type.number_of_product_day
      column_chart OrderDetail.by_day(@day).number_of_product_chart_data
    when Settings.chart_type.number_of_product_month
      column_chart OrderDetail.by_month(@day).number_of_product_chart_data
    when Settings.chart_type.number_of_product_year
      column_chart OrderDetail.by_year(@day).number_of_product_chart_data
    when Settings.chart_type.income_of_product_day
      column_chart OrderDetail.by_day(@day).income_of_product_chart_data
    when Settings.chart_type.income_of_product_month
      column_chart OrderDetail.by_month(@day).income_of_product_chart_data
    when Settings.chart_type.income_of_product_year
      column_chart OrderDetail.by_year(@day).income_of_product_chart_data
    when Settings.chart_type.income_daily
      line_chart OrderDetail.income_daily
    when Settings.chart_type.income_monthy
      line_chart OrderDetail.income_monthy
    else
      line_chart OrderDetail.income_yearly
    end
  end
end

app/views/admin/statistics/index.html.erb
<div class="row">
  <h2><%= statistic_select[@select.to_i-1].first %></h2>
</div>
<div class="row">
  <aside class="col-md-4">
    <%= form_tag admin_statistics_path, method: :get do %>
      <div class="form-group">
        <label for="date"><%= t "statistic.choose_day" %></label>
        <%= date_field_tag :date, Date.today, class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="date">Statistic</label>
        <%= select_tag :statistic,
          options_for_select(statistic_select, params[:statistic]), include_blank: nil,
          class: "select form-control" %>
      </div>
      <%= submit_tag t("statistic.get_statistic"), class: "btn btn-info" %>
    <% end %>
  </aside>
  <div class="col-md-8">
    <%= render_chart @select.to_i %>
  </div>
</div>