config/routes.rb
Rails.application.routes.draw do
  get "categories/index"

  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  get "/carts", to: "carts#index"
  post "/carts", to: "carts#create"
  put "/carts", to: "carts#update"
  delete "/carts", to: "carts#destroy"
  resources :users do
    resources :suggested_products
    resources :orders, only: [:show]
  end
  resources :products do
    resources :ratings, only: :create
  end
  resources :carts, only: :index
  resources :orders
  resources :order_confirmations, only: :edit
  namespace :admin do
    resources :products do
      collection {post :import}
    end
    resources :users, only: [:index, :destroy]
    resources :orders
    resources :suggested_products, only: [:index, :destroy]
    resources :statistics
    resources :categories
    resources :sub_categories
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :sub_category
  belongs_to :classification
  has_many :order_details, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy

  mount_uploader :image, ProductUploader
  validates :name, presence: true, length: {maximum: Settings.validation.name}
  validates :description, presence: true,
    length: {maximum: Settings.validation.content}
  validates :price, presence: true,
    numericality: {greater_than_or_equal_to: Settings.validation.price}
  validates :quantity, presence: true, numericality: {only_integer: true}
  validates :sub_category_id, presence: true
  validates :classification_id, presence: true
  validates :image, presence: true

  scope :by_sub_category, ->sub_category_id do
    where sub_category_id: sub_category_id if sub_category_id.present?
  end

  scope :by_name, ->name do
    where "name LIKE '%#{name}%'" if name.present?
  end

  scope :by_min_price, ->min do
    where "price >= #{min}" if min.present?
  end

  scope :by_max_price, ->max do
    where "price <= #{max}" if max.present?
  end

  scope :by_classification, ->classification_id do
    where classification_id: classification_id if classification_id.present?
  end

  scope :top_order_products, -> {
    left_outer_joins(:order_details)
    .group("products.id")
    .order("count(order_details.id) desc")}

  scope :top_new_products, -> {order "created_at desc"}

  def self.import? file
    begin
      ActiveRecord::Base.transaction do
        CSV.foreach(file.path, headers: true) do |row|
          product = Product.new row.to_h
          product.image = open "public/uploads/product/image/1/#{row.to_h["image"]}"
          product.save!
        end
      end
    rescue ActiveRecord::RecordInvalid
      return false
    end
    true
  end

  def average_rate
    ((ratings.to_a.sum {|item| item.point}).to_f/ratings.count).
      round((Settings.average_rate_round))
  end

  def get_rating_by_user user
    rating = ratings.find_by user: user
    rating.present? ? rating.point : nil
  end

  def rate_count
    ratings.count
  end

  def is_out_of_stock? order_quantity
    quantity < order_quantity
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :admin_user
  before_action :load_product, only: [:edit, :update, :destroy, :show]
  before_action :get_price_params, only: :index
  before_action :load_all_product, only: :index

  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
    if @product.update_attributes product_params
      flash[:success] = t "success.update"
      redirect_to [:admin, @product]
    else
      flash[:danger] = t "error.update_failed"
      redirect_to admin_products_path
    end
  end

  def show
  end

  def destroy
    if @product.destroy
      flash.now[:success] = t "success.delete"
      load_all_product
      respond_to do |format|
        format.js
      end
    else
      flash.now[:danger] = t "error.detele"
      load_all_product
      respond_to do |format|
        format.js
      end
    end
  end

  def import
    if Product.import?(params[:file])
      flash[:success] = t "success.upload"
    else
      flash[:danger] = t "error.upload"
      redirect_to admin_products_path
    end
  end

  private

  def product_params
    params.require(:product).permit :name, :description, :price, :quantity,
      :image, :sub_category_id
  end

  def load_product
    @product = Product.find_by id: params[:id]
    unless @product
      flash[:danger] = t "error.product_not_found"
      redirect_to admin_products_path
    end
  end

  def load_all_product
    @products = Product.by_sub_category(params[:sub_category])
      .by_classification(params[:classsification])
      .by_name(params[:name])
      .by_min_price(@min_price)
      .by_max_price(@max_price)
    if params[:rate].present?
      @products = @products.select do |product|
        product.average_rate >= params[:rate].to_i
      end
    end
    @products = @products.paginate page: params[:page],
      per_page: Settings.paginate.admin_products
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_product, only: :show
  before_action :get_price_params, only: :index

  def index
    @products = Product.by_sub_category(params[:sub_category])
      .by_name(params[:name])
      .by_min_price(@min_price)
      .by_max_price(@max_price)
    if params[:rate].present?
      @products = @products.select do |product|
        product.average_rate >= params[:rate].to_i
      end
    end
    @products = @products.paginate page: params[:page],
      per_page: Settings.paginate.product_show
  end

  def show
    if logged_in?
      @rating = Rating.find_by product_id: params[:id],
        user_id: current_user.id
    end
    recently_viewed_products.push @product
  end

  private
  def load_product
    @product = Product.find_by id: params[:id]
    unless @product
      flash[:danger] = t "error.product_not_found"
      redirect_to root_url
    end
  end

  def get_price_params
    price_str = params[:price]
    @max_price = price_str.split(",").last if price_str.present?
    @min_price = price_str.split(",").first if price_str.present?
  end
end

app/helpers/products_helper.rb
module ProductsHelper

  def recently_viewed_products
    @recently_viewed_products ||= RecentlyViewedProduct.new(cookies)
  end
end

app/views/admin/products/_form.html.erb
<div class="row">
  <h1 class="text-center"><%= yield :title %></h1>
</div>
<div class="row">
  <%= form_for [:admin, @product], html: { multipart: true } do |f| %>
    <%= render "shared/error_messages", object: f.object%>
    <div class="col-md-5 col-md-offset-2">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div>
        <%= t "search.category" %><%= f.select :sub_category_id,
          grouped_options_for_select(group_category_select),
          {include_blank: nil}, {class: "select form-control"} %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :price %>
        <div class="input-group">
          <span class="input-group-addon"><%= number_to_currency 1,
            format: "%u" %></span>
          <%= f.number_field :price, class: "form-control",
            min: Settings.product_form.min_price,
            step: Settings.product_form.price_step %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :quantity %>
        <div class="input-group">
          <%= f.number_field :quantity, class: "form-control",
            min: Settings.product_form.quantity_min,
            step: Settings.product_form.quantity_step %>
        </div>
      </div>
    </div>
    <div class="col-md-5">
      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image, id: "image-upload" %>
        <% if @product.image.present? %>
          <%= image_tag @product.image.url, alt: "logo",
            class: "img-responsive",
            id: "current-profile-image"%>
        <% end %>
        <%= image_tag "#", {size: Settings.image.product_upload_size,
          alt: "suggested product image",
          class: "img-thumbnail hidden", id: "img_prev"} %>
      </div>
    </div>
    <div class="col-md-5 col-md-offset-2">
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/admin/products/_list_product.html.erb
<% if products.any? %>
  <%= render products %>
  <%= will_paginate %>
<% else %>
  <p class="text-info"><%= t "info.no_product" %></p>
<% end %>

app/views/admin/products/_product.html.erb
<div class="card col-sm-6 col-md-3">
  <%= link_to image_tag(product.image.url, alt: t("alt.product_image"),
    class: "full-width-image"), [:admin, product] %>
    <h4><b><%= product.name %></b></h4>
    <div class="product-rate"
      data-score="<%= product.average_rate %>">
    </div>
    <span>( <%= pluralize product.rate_count, "reviews" %> )</span>
    <p class="product-price"><%= t "product.price" %>
      <%= number_to_currency product.price %>
    </p>
    <%= link_to t("button.delete"), admin_product_path(product),
      class: "inline-btn btn btn-success", method: :delete,
      data: { confirm: t("confirm.are_you_sure") }, remote: true %>
    <%= link_to t("button.edit"), edit_admin_product_path(product),
      class: "inline-btn btn btn-success" %>
</div>

app/views/admin/products/_upload.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="upload-modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"
          aria-label="<%= t "upload.close" %>">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title"><%= t "upload.title" %></h4>
      </div>
      <div class="modal-body">
        <%= form_tag import_admin_products_path, multipart: true,
          class: "form-group", id: "import-form" do %>
          <%= file_field_tag :file %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
          <%= t "upload.cancel" %>
        </button>
        <button type="submit" form="import-form" class="btn btn-primary">
          <%= t "upload.import" %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/destroy.js.erb
<% if @product.destroyed? %>
  $('#flash').html('<div class="alert alert-success"><%= flash[:success] %></div>')
  $('.products').html('<%= j render partial: "list_product", locals: {products: @products} %>')
<% else %>
  $('#flash').html('<div class="alert alert-danger"><%= flash[:danger] %></div>')
  $('.products').html('<%= j render partial: "list_product", locals: {products: @products} %>')
<% end %>

app/views/admin/products/edit.html.erb
<%= provide :title, t("edit_product.title") %>
<%= provide :button_text, t("button.save_changes") %>
<%= render "form" %>

app/views/admin/products/index.html.erb
<% provide :path, admin_products_path %>
<div class = "row product-list">
  <hr>
  <aside class="col-md-2">
    <%= render "shared/search_form" %>
  </aside>
  <div class="col-md-10 products">
    <%= render partial: "list_product", locals: {products: @products} %>
  </div>
</div>
<%= render "upload" %>

app/views/admin/products/show.html.erb
<% provide :og_url, "http://www.notes.minamidev.com" %>
<% provide :og_type, "article" %>
<% provide :og_title, @product.name %>
<% provide :og_description, @product.description %>
<% provide :og_image, "http://www.levihackwith.com/wp-content/uploads/2013/03/ruby.png" %>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <%= image_tag @product.image.url, alt: t("alt.product_image"),
        class: "img-responsive" %>
    </div>
    <div class="col-md-6">
      <h2><%= @product.name %>
      </h2>
      <div class="row admin-rate-product" product-id="<%= @product.id %>"
        data-score="<%= @product.average_rate %>">
      </div>
      <i><%= pluralize @product.rate_count, "review" %></i>
      <p class="description"><%= @product.description %></p>
      <%= render "layouts/facebook_share" %>
      <h3 class="price"><%= number_to_currency @product.price %></h3>
      <%= link_to t("button.edit"), edit_admin_product_path(@product),
        class: "btn btn-default" %>
      <%= link_to t("button.delete"), admin_product_path(@product),
        method: :delete, data: { confirm: t("confirm.are_you_sure") },
        class: "btn btn-danger" %>
    </div>
  </div>
</div>