config/routes.rb
Rails.application.routes.draw do
  get "categories/index"

  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  get "/carts", to: "carts#index"
  post "/carts", to: "carts#create"
  put "/carts", to: "carts#update"
  delete "/carts", to: "carts#destroy"
  resources :users do
    resources :suggested_products
    resources :orders, only: [:show]
  end
  resources :products do
    resources :ratings, only: :create
  end
  resources :carts, only: :index
  resources :orders
  resources :order_confirmations, only: :edit
  namespace :admin do
    resources :products do
      collection {post :import}
    end
    resources :users, only: [:index, :destroy]
    resources :orders
    resources :suggested_products, only: [:index, :destroy]
    resources :statistics
    resources :categories
    resources :sub_categories
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  has_many :comments, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :suggested_products, dependent: :destroy
  has_many :ratings, dependent: :destroy

  mount_uploader :profile_image, UserUploader

  validates :user_name, presence: true,
    length: {minimum: Settings.validation.user_name_min,
    maximum: Settings.validation.user_name_max}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
    length: {maximum: Settings.validation.email},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true,
    length: {minimum: Settings.validation.password}, allow: nil
  validates :profile_image, presence: true
  before_save {email.downcase!}

  scope :order_by_name, -> {order "user_name"}

  scope :by_name_email, ->keyword do
    where "user_name LIKE '%#{keyword}%' OR email LIKE '%#{keyword}%'" if keyword.present?
  end

  def self.digest string
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create string, cost: cost
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute :remember_digest, User.digest(remember_token)
  end

  def forget
    update_attribute :remember_digest, nil
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    if digest.nil?
      false
    else
      BCrypt::Password.new(digest).is_password? token
    end
  end

  def is_user? user
    self == user
  end

  private
  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user
  before_action :load_user, only: :destroy
  before_action :load_all_user, only: :index
  def index
  end

  def destroy
    if @user.destroy
      flash[:success] = t "success.delete"
      load_all_user
      respond_to do |format|
        format.js
      end
    else
      flash[:danger] = t "error.delete"
      load_all_user
      respond_to do |format|
        format.js
      end
    end
  end

  private

  def load_user
    @user = User.find_by id: params[:id]
    unless @user
      flash[:danger] = "error.user_not_found"
      redirect_to admin_users
    end
  end

  def load_all_user
    @users = User.by_name_email(params[:keyword]).paginate page: params[:page],
      per_page: Settings.paginate.admin_users
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [:show, :update]
  before_action :correct_user, only: [:edit, :update, :show]
  before_action :logged_in_user, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      login @user
      flash[:success] = t "success.signup"
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @recently_viewed_products = recently_viewed_products.reverse
      .paginate page: params[:page], per_page: Settings.paginate.recently_viewed
    @orders = current_user.orders.paginate page: params[:order_page],
      per_page: Settings.paginate.user_orders
    @suggested_products = current_user.suggested_products.paginate page: params[:suggest_page],
      per_page: Settings.paginate.suggested_products
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "success.update"
      redirect_to @user
    else
      flash[:danger] = t "error.update_failed"
      render :edit
    end
  end

  private
  def load_user
    @user = User.find_by id: params[:id]
    unless @user
      flash[:danger] = t "error.user_not_found"
      redirect_to root_url
    end
  end

  def user_params
    params.require(:user).permit :user_name, :email, :password,
      :password_confirmation, :profile_image
  end

  def correct_user
    @user = User.find_by id: params[:id]
    if @user.nil?
      flash[:danger] = t "user_not_found"
      redirect_to root_url
    else
      unless @user == current_user
        flash[:danger] = t "user_not_found"
        redirect_to root_url
      end
    end
  end
end

app/views/admin/users/_list_user.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="user-table">
    <table class="table ecommerce-table">
      <thead>
        <tr>
          <th><%= t "table.user" %></th>
          <th><%= t "table.user_name" %></th>
          <th><%= t "table.email" %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% users.each do |user| %>
          <%= render partial: "user_table", locals: {user: user} %>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate users %>
  </div>
</div>

app/views/admin/users/_user_table.html.erb
<tr class="user-row">
  <td class="w20">
    <%= image_tag user.profile_image.url, alt: t("alt.profile_image"),
      class: "img-responsive" %>
  </td>
  <td class="w20">
    <strong><%= user.user_name %></strong>
  </td>
  <td class="w45">
    <%= user.email %>
  </td>
  <td>
    <% if !user.is_user? current_user %>
      <%= link_to "Delete",admin_user_path(user), method: :delete,
        data: { confirm: "Are you sure?" }, class: "text-danger", remote: true %>
    <% end %>
  </td>
</tr>

app/views/admin/users/destroy.js.erb
<% if @user.destroyed? %>
  $('#flash').html('<div class="alert alert-success"><%= flash[:success] %></div>')
  $('tbody').html('<%= j render partial: "list_user", locals: {users: @users} %>')
<% else %>
  $('#flash').html('<div class="alert alert-danger"><%= flash[:danger] %></div>')
  $('tbody').html('<%= j render partial: "list_user", locals: {users: @users} %>')
<% end %>

app/views/admin/users/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h2><%= t "user_management.title" %></h2>
    <%= form_tag admin_users_path, method: :get, id: "seach-user", class: "search-box" do %>
        <input type="text" name="keyword" class="form-control search-query"
          placeholder="<%= t "user_management.placeholder" %>" />
        <button class="btn btn-danger" form="seach-user" type="submit">
          <%= t "button.search" %>
        </button>
      </div>
    <% end %>
  </div>
</div>
<div class="row">
  <% if @users.any? %>
    <%= render partial: "list_user", locals: {users: @users} %>
  <% else %>
  <div class="col-md-8 col-md-offset-2">
    <div class="alert alert-danger no-user-info">
      <p class="text-center"><%= t "info.no_user" %></p>
    </div>
  </div>
  <% end %>
</div>